use Game;

CREATE TABLE [Players] (
  [Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  [Login] varchar(100) UNIQUE NOT NULL
)
GO

CREATE TABLE [PlayerStatistics] (
  [PlayerId] UNIQUEIDENTIFIER PRIMARY KEY,
  [Winrate] FLOAT DEFAULT 0,
  CONSTRAINT FK_PlayerStatistics_Players_Id FOREIGN KEY (PlayerId) REFERENCES Players(Id) ON DELETE CASCADE
)
GO

CREATE TABLE [Units] (
  [Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  [Name] varchar(100) NOT NULL,
  [Type] varchar(100) NOT NULL,
  [Data] varchar(1000) NOT NULL
)
GO

CREATE TABLE [Items] (
  [Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  [Name] varchar(100) UNIQUE NOT NULL,
  [Cost] int,
  [Type] int NOT NULL,
  [Data] varchar(1000) NOT NULL
)
GO

CREATE TABLE [Terrains] (
  [Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  [Name] varchar(100) NOT NULL,
  [Penalty] int
)
GO

CREATE TABLE [Maps] (
  [Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  [Name] varchar(100) UNIQUE NOT NULL,
  [Width] INT NOT NULL,
  [Height] INT NOT NULL
)
GO

CREATE TABLE [Cells] (
  [Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  [X] int NOT NULL,
  [Y] int NOT NULL,
  [MapId] UNIQUEIDENTIFIER NOT NULL,
  [TerrainId] UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT FK_Cells_Maps_CellId FOREIGN KEY ([MapId]) REFERENCES [Maps]([Id]) ON DELETE CASCADE,
  CONSTRAINT FK_Cells_Terrains_TerrainId FOREIGN KEY ([TerrainId]) REFERENCES [Terrains]([Id]),
)
GO

CREATE TABLE [Heroes] (
  [Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  [Name] varchar(100) UNIQUE NOT NULL,
  [Type] int UNIQUE NOT NULL,
  [Health] int NOT NULL,
  [MovingEnergy] int NOT NULL,
  [Description] varchar(1000) NOT NULL,
  [Data] varchar(1000) NOT NULL
)
GO

CREATE TABLE Games (
  Id UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  Name varchar(100) NOT NULL,
  MapId UNIQUEIDENTIFIER,
  StartedAt datetime NOT NULL DEFAULT (GETDATE()),
  EndedAt DATETIME,
  WinnerId UNIQUEIDENTIFIER
  CONSTRAINT FK_Games_Maps_MapId FOREIGN KEY ([MapId]) REFERENCES [Maps](Id) ON DELETE NO ACTION,
  CONSTRAINT FK_Games_Players_PlayerId FOREIGN KEY ([WinnerId]) REFERENCES [Players]([Id]) ON DELETE NO ACTION,
  CHECK (EndedAt > StartedAt)
)
GO

CREATE TABLE [Parties] (
	[PlayerId] UNIQUEIDENTIFIER,
	[GameId] UNIQUEIDENTIFIER,
	[HeroId] UNIQUEIDENTIFIER,
	[Score] int DEFAULT (0),
	PRIMARY KEY ([PlayerId], [GameId]),
	CONSTRAINT FK_Parties_Players_PlayerId FOREIGN KEY ([PlayerId]) REFERENCES [Players]([Id]) ON DELETE NO ACTION,
    CONSTRAINT FK_Parties_Games_GameId FOREIGN KEY ([GameId]) REFERENCES [Games]([Id]) ON DELETE NO ACTION,
	CONSTRAINT FK_Parties_Heroes_HeroId FOREIGN KEY ([HeroId]) REFERENCES [Heroes]([Id]) ON DELETE NO ACTION,
)
GO

CREATE TABLE [UnitCellPositions] (
	[UnitId] UNIQUEIDENTIFIER,
	[CellId] UNIQUEIDENTIFIER,
	PRIMARY KEY ([UnitId], [CellId]),
	CONSTRAINT FK_UnitCellPositions_Units_UnitId FOREIGN KEY ([UnitId]) REFERENCES [Units]([Id]),
	CONSTRAINT FK_UnitCellPositions_Cells_CellId FOREIGN KEY ([CellId]) REFERENCES [Cells]([Id]) ON DELETE CASCADE,
)
GO

CREATE TABLE [HeroeBaseItems] (
	[HeroId] UNIQUEIDENTIFIER,
	[ItemId] UNIQUEIDENTIFIER,
	PRIMARY KEY ([HeroId], [ItemId]),
  	CONSTRAINT FK_HeroeBaseItems_Heroes_HeroId FOREIGN KEY ([HeroId]) REFERENCES [Heroes]([Id]) ON DELETE CASCADE,
	CONSTRAINT FK_HeroeBaseItems_Heroes_ItemId FOREIGN KEY ([ItemId]) REFERENCES [Items]([Id]),
)
GO